name: Autorelease

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Retrieve the latest version from the GitHub API.
      run: |
        LATEST_TAG=$(curl -s "https://api.github.com/repos/avighnac/arithmetica-tui/releases/latest" | jq -r '.tag_name')
        echo $LATEST_TAG
    - name: Calculate the autorelease number with the help of the GitHub API.
      run: |
        echo https://api.github.com/repos/avighnac/arithmetica-tui/compare/$LATEST_TAG...HEAD
        GITHUB_API_URL=$(echo https://api.github.com/repos/avighnac/arithmetica-tui/compare/$LATEST_TAG...HEAD)
        echo $GITHUB_API_URL
        AUTORELEASE_NO=$(curl -s $GITHUB_API_URL | jq -r '.total_commits')
        echo $AUTORELEASE_NO
    - name: Modify main.cpp
      run: sed -i "s/std::string autorelease = \".*\";/std::string autorelease = \"${AUTORELEASE_NO}\";/" src/main.cpp
    - name: Download arithmetica and basic_math_operations
      run: |
        curl -s -H "Accept: application/vnd.github.v3.raw" https://api.github.com/repos/avighnac/arithmetica/contents/install.sh | sudo bash
        curl -s -H "Accept: application/vnd.github.v3.raw" https://api.github.com/repos/avighnac/basic_math_operations/contents/install.sh | sudo bash
    - name: Compile arithmetica for a GitHub release
      run: |
        cmake --no-warn-unused-cli -DBUILD_RELEASE=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_BUILD_TYPE=Release -S . -B build -G "Unix Makefiles"
        cmake --build build --config Release --target all -j 10 --
    - name: Make a variable for the release name
      run: |
        echo "RELEASE_NAME=$(echo $LATEST_TAG-alpha-$AUTORELEASE_NO)" >> $GITHUB_ENV
        echo $RELEASE_NAME
    - name: Create a GitHub (pre)release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_NAME }}
        release_name: ${{ env.RELEASE_NAME }}
        draft: false
        prerelease: true
    - name: Upload executable for Linux.
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/src/arithmetica
        asset_name: arithmetica.out
        asset_content_type: application/x-executable
